name: auto-rag

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8005:8000"
    working_dir: /app
    gpus: all
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
      - ./temp:/app/temp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8005
    ports:
      - "3000:3000"
    depends_on:
      - backend
