"""video_job_stage_progress_error

Revision ID: 91d83818410b
Revises: af24aac2c22e
Create Date: 2026-04-24 11:40:17.683041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d83818410b'
down_revision: Union[str, None] = 'af24aac2c22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('current_stage', sa.String(length=64), nullable=True))
    op.add_column('video_jobs', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('video_jobs', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'last_error')
    op.drop_column('video_jobs', 'progress_percent')
    op.drop_column('video_jobs', 'current_stage')
    # ### end Alembic commands ###
